baseURL = 'https://joyschoolco.com/'
languageCode = 'en-us'
title = 'The Joy School Curriculum Company'
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'