text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Curriculm and resources for the Joyschool program"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-green"
recent_posts_number = 3

[ananke]
show_recent_posts = false