version: '3.7'

services:
  server:
    image: klakegg/hugo:ext
    command: server
#    pull_policy: always
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"

  build:
    image: klakegg/hugo:ext
    command: mod init github.com/jloosli/joyschoolco.com
    volumes:
      - ".:/src"
