name: joyschoolco.com site
services:
  server:
    image: hugomods/hugo:exts-non-root
    command: server -D
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313

  build:
    image: klakegg/hugo:ext
    command: mod init github.com/jloosli/joyschoolco.com
    volumes:
      - ".:/src"
